export const MENUS = '/api/menus'
export const MEETINGS = '/api/meetings'
export const NOTIFICATIONS = '/api/notifications'
export const STATEMENTS = '/api/statements'
export const PORTALS = '/api/portals'
