export const ARTICLES = '/api/articles'
export const CONTENT = '/api/content'
export const GBF_TARGETS = '/api/gbf-targets'
export const MEETINGS = '/api/meetings'
export const NOTIFICATIONS = '/api/notifications'
export const PORTALS = '/api/portals'
export const STATEMENTS = '/api/statements'
