services:
  cache.backend.redis:
    class: Drupal\redis\Cache\CacheBackendFactory
    arguments:
      [
        "@redis.factory",
        "@cache_tags_provider.container",
        "@serialization.phpserialize",
      ]
  cache_tags_provider.container:
    class: Drupal\redis\Cache\RedisCacheTagsChecksum
    arguments: ["@redis.factory"]
  redis.factory:
    class: Drupal\redis\ClientFactory
